# Description: Configuration file for the python-services

#absolute path
socket_directory:   /tmp/python-services

#relative path
python_executable:  .venv/bin/python3

#relative path
service_directory:  services
services_csv:       services.csv

#options
clear_socket:       True
stop_services:      True